import { AnimUnit, AnimCategory } from './types'

export const animationUnits: readonly AnimUnit[] = [
  {
    category: AnimCategory.A,
    id: 'a-1',
    frameLength: 12,
    spriteSheetLength: 3,
    sound: 'web_ A_DR 1',
  },
  {
    category: AnimCategory.A,
    id: 'a-2',
    frameLength: 19,
    spriteSheetLength: 3,
    sound: 'web_ A_DR 2',
  },
  {
    category: AnimCategory.A,
    id: 'a-3',
    frameLength: 37,
    spriteSheetLength: 5,
    sound: 'web_ A_DR 3',
  },
  {
    category: AnimCategory.A,
    id: 'ab-1',
    frameLength: 18,
    spriteSheetLength: 7,
    sound: 'web_ A_DR 4',
  },
  {
    category: AnimCategory.B,
    id: 'b-1',
    frameLength: 15,
    spriteSheetLength: 4,
    sound: 'web_ B_BS 1',
  },
  {
    category: AnimCategory.B,
    id: 'b-2',
    frameLength: 22,
    spriteSheetLength: 3,
    sound: 'web_ B_BS 2',
  },
  {
    category: AnimCategory.B,
    id: 'b-3',
    frameLength: 23,
    spriteSheetLength: 6,
    sound: 'web_ B_BS 3',
  },
  {
    category: AnimCategory.C,
    id: 'b-4',
    frameLength: 1,
    spriteSheetLength: 1,
    sound: 'web_ C_MEL 1',
  },
  {
    category: AnimCategory.C,
    id: 'b-5',
    frameLength: 23,
    spriteSheetLength: 8,
    sound: 'web_ C_MEL 2',
  },
  {
    category: AnimCategory.C,
    id: 'bc-1',
    frameLength: 16,
    spriteSheetLength: 4,
    sound: 'web_ C_MEL 3',
  },
  {
    category: AnimCategory.C,
    id: 'c-1',
    frameLength: 14,
    spriteSheetLength: 6,
    sound: 'web_ C_MEL 4',
  },
  {
    category: AnimCategory.D,
    id: 'c-2',
    frameLength: 21,
    spriteSheetLength: 10,
    sound: 'web_ D_FX 1',
  },
  {
    category: AnimCategory.D,
    id: 'c-3',
    frameLength: 12,
    spriteSheetLength: 7,
    sound: 'web_ D_FX 2',
  },
  {
    category: AnimCategory.D,
    id: 'c-4',
    frameLength: 56,
    spriteSheetLength: 18,
    sound: 'web_ D_FX 3',
  },
  {
    category: AnimCategory.D,
    id: 'c-5',
    frameLength: 26,
    spriteSheetLength: 12,
    sound: 'web_ D_FX 4',
  },
  {
    category: AnimCategory.E,
    id: 'cd-1',
    frameLength: 18,
    spriteSheetLength: 4,
    sound: 'web_ E_AMBIENT 1',
  },
  {
    category: AnimCategory.E,
    id: 'd-1',
    frameLength: 10,
    spriteSheetLength: 3,
    sound: 'web_ E_AMBIENT 2',
  },
  {
    category: AnimCategory.E,
    id: 'd-2',
    frameLength: 14,
    spriteSheetLength: 7,
    sound: 'web_ E_AMBIENT 3',
  },
  {
    category: AnimCategory.E,
    id: 'd-3',
    frameLength: 20,
    spriteSheetLength: 4,
    sound: 'web_ E_AMBIENT 4',
  },
  {
    id: 'd-4',
    frameLength: 25,
    spriteSheetLength: 8,
  },
  {
    id: 'de-1',
    frameLength: 15,
    spriteSheetLength: 7,
  },
  {
    id: 'e-1',
    frameLength: 10,
    spriteSheetLength: 2,
  },
  {
    id: 'e-2',
    frameLength: 20,
    spriteSheetLength: 13,
  },
  {
    id: 'e-3',
    frameLength: 20,
    spriteSheetLength: 15,
  },
  {
    id: 'ef-1',
    frameLength: 13,
    spriteSheetLength: 5,
  },
  {
    id: 'eg-1',
    frameLength: 28,
    spriteSheetLength: 6,
  },
  {
    id: 'eg-2',
    frameLength: 23,
    spriteSheetLength: 11,
  },
  {
    id: 'eg-3',
    frameLength: 41,
    spriteSheetLength: 5,
  },
  {
    id: 'eg-4',
    frameLength: 45,
    spriteSheetLength: 8,
  },
  {
    id: 'f-1',
    frameLength: 12,
    spriteSheetLength: 2,
  },
  {
    id: 'f-2',
    frameLength: 29,
    spriteSheetLength: 11,
  },
  {
    id: 'f-3',
    frameLength: 60,
    spriteSheetLength: 24,
  },
  {
    id: 'f-4',
    frameLength: 43,
    spriteSheetLength: 17,
  },
  {
    id: 'f-5',
    frameLength: 32,
    spriteSheetLength: 3,
  },
  {
    id: 'f-6',
    frameLength: 32,
    spriteSheetLength: 11,
  },
  {
    id: 'fg-1',
    frameLength: 19,
    spriteSheetLength: 4,
  },
  {
    id: 'g-1',
    frameLength: 10,
    spriteSheetLength: 3,
  },
  {
    id: 'g-2',
    frameLength: 56,
    spriteSheetLength: 6,
  },
  {
    id: 'g-3',
    frameLength: 27,
    spriteSheetLength: 1,
  },
  {
    id: 'g-4',
    frameLength: 25,
    spriteSheetLength: 3,
  },
  {
    id: 'gj-1',
    frameLength: 13,
    spriteSheetLength: 6,
  },
  {
    id: 'h-1',
    frameLength: 10,
    spriteSheetLength: 5,
  },
  {
    id: 'i-1',
    frameLength: 6,
    spriteSheetLength: 2,
  },
  {
    id: 'i-2',
    frameLength: 61,
    spriteSheetLength: 1,
  },
  {
    id: 'j-1',
    frameLength: 10,
    spriteSheetLength: 3,
  },
  {
    id: 'j-2',
    frameLength: 49,
    spriteSheetLength: 6,
  },
  {
    id: 'j-3',
    frameLength: 59,
    spriteSheetLength: 8,
  },
  {
    id: 'j-4',
    frameLength: 15,
    spriteSheetLength: 5,
  },
  {
    id: 'j-5',
    frameLength: 15,
    spriteSheetLength: 4,
  },
  {
    id: 'j-6',
    frameLength: 26,
    spriteSheetLength: 3,
  },
  {
    id: 'j-7',
    frameLength: 26,
    spriteSheetLength: 21,
  },
  {
    id: 'jl-1',
    frameLength: 14,
    spriteSheetLength: 7,
  },
  {
    id: 'k-1',
    frameLength: 12,
    spriteSheetLength: 5,
  },
  {
    id: 'l-1',
    frameLength: 13,
    spriteSheetLength: 2,
  },
  {
    id: 'l-2',
    frameLength: 40,
    spriteSheetLength: 8,
  },
  {
    id: 'l-3',
    frameLength: 40,
    spriteSheetLength: 8,
  },
  {
    id: 'l-4',
    frameLength: 41,
    spriteSheetLength: 11,
  },
  {
    id: 'l-5',
    frameLength: 17,
    spriteSheetLength: 8,
  },
  {
    id: 'l-6',
    frameLength: 14,
    spriteSheetLength: 2,
  },
  {
    id: 'l-7',
    frameLength: 36,
    spriteSheetLength: 12,
  },
  {
    id: 'l-8',
    frameLength: 102,
    spriteSheetLength: 17,
  },
  {
    id: 'l-9',
    frameLength: 53,
    spriteSheetLength: 21,
  },
  {
    id: 'lm-1',
    frameLength: 20,
    spriteSheetLength: 12,
  },
  {
    id: 'm-1',
    frameLength: 12,
    spriteSheetLength: 3,
  },
  {
    id: 'm-2',
    frameLength: 23,
    spriteSheetLength: 4,
  },
  {
    id: 'm-3',
    frameLength: 23,
    spriteSheetLength: 9,
  },
  {
    id: 'n-1',
    frameLength: 14,
    spriteSheetLength: 2,
  },
  {
    id: 'n-2',
    frameLength: 28,
    spriteSheetLength: 7,
  },
  {
    id: 'n-3',
    frameLength: 28,
    spriteSheetLength: 3,
  },
  {
    id: 'n-4',
    frameLength: 40,
    spriteSheetLength: 15,
  },
  {
    id: 'o-1',
    frameLength: 11,
    spriteSheetLength: 5,
  },
  {
    id: 'p-1',
    frameLength: 14,
    spriteSheetLength: 2,
  },
  {
    id: 'q-1',
    frameLength: 12,
    spriteSheetLength: 3,
  },
]
